CREATE TABLE RUBRIC(
   ID INT IDENTITY,
   NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE _USER(
   ID INT IDENTITY,
   NAME VARCHAR(30),
   FIRST_NAME VARCHAR(30),
   NICK_NAME VARCHAR(30) NOT NULL,
   PH_NO VARCHAR(20),
   PHOTO VARBINARY(max),
   E_MAIL VARCHAR(75),
   MODERATOR_Y_N BIT NOT NULL,
   PASSWORD VARCHAR(200) NOT NULL,
   COUNT_REPLIES INT,
   COUNT_SUBJECTS INT,
   PRIMARY KEY(ID),
   UNIQUE(E_MAIL)
);

CREATE TABLE TOPIC(
   ID INT IDENTITY,
   TITLE VARCHAR(500) NOT NULL,
   TEXT_PUB VARCHAR(max) NOT NULL,
   PUB_DATE DATETIME2 NOT NULL,
   DELETED BIT NOT NULL,
   ID_USER INT NOT NULL,
   ID_RUBRIC INT NOT NULL,
   PRIMARY KEY(ID),
   FOREIGN KEY(ID_USER) REFERENCES _USER(ID),
   FOREIGN KEY(ID_RUBRIC) REFERENCES RUBRIC(ID)
);

CREATE TABLE REPLY(
   ID INT IDENTITY,
   TEXT VARCHAR(max) NOT NULL,
   REPLY_DATE DATETIME2 NOT NULL,
   DELETED BIT NOT NULL,
   ID_PARENT_REPLY INT,
   ID_USER INT NOT NULL,
   ID_TOPIC INT NOT NULL,
   PRIMARY KEY(ID),
   FOREIGN KEY(ID_PARENT_REPLY) REFERENCES REPLY(ID),
   FOREIGN KEY(ID_USER) REFERENCES _USER(ID),
   FOREIGN KEY(ID_TOPIC) REFERENCES TOPIC(ID)
);
