using Domain.Entites;
using System.Threading.Tasks;

namespace BLL
{
    public interface ISecurityService
    {
        /// <summary>
        /// Returns the token generated by the server
        /// </summary>
        /// <param name="username">nickname</param>
        /// <param name="password"></param>
        /// <returns></returns>
        Task<string> SigningAsync(string login_name, string password);
    }
}